use territoryState
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"2","stateName":"Alaska"});
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"5","stateName":"American Samoa"});
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"21","stateName":"Hawaii"});
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"23","stateName":"Idaho"});
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"40","stateName":"Montana"});
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"52","stateName":"Nevada"});
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"58","stateName":"Oregon"});
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"74","stateName":"Utah"});
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"82","stateName":"Wyoming"});
db.territoryState.save({"territoryID":"1","territoryName":"Northwest","stateID":"79","stateName":"Washington"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"78","stateName":"Vermont"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"59","stateName":"Pennsylvania"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"54","stateName":"New York"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"55","stateName":"Ohio"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"65","stateName":"Rhode Island"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"46","stateName":"New Hampshire"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"47","stateName":"New Jersey"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"32","stateName":"Maryland"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"33","stateName":"Maine"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"25","stateName":"Indiana"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"30","stateName":"Massachusetts"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"11","stateName":"Connecticut"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"12","stateName":"District of Columbia"});
db.territoryState.save({"territoryID":"2","territoryName":"Northeast","stateID":"13","stateName":"Delaware"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"10","stateName":"Colorado"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"4","stateName":"Arkansas"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"28","stateName":"Louisiana"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"35","stateName":"Michigan"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"36","stateName":"Minnesota"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"37","stateName":"Missouri"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"26","stateName":"Kansas"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"24","stateName":"Illinois"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"22","stateName":"Iowa"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"43","stateName":"North Dakota"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"44","stateName":"Nebraska"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"68","stateName":"South Dakota"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"56","stateName":"Oklahoma"});
db.territoryState.save({"territoryID":"3","territoryName":"Central","stateID":"80","stateName":"Wisconsin"});
db.territoryState.save({"territoryID":"4","territoryName":"Southwest","stateID":"73","stateName":"Texas"});
db.territoryState.save({"territoryID":"4","territoryName":"Southwest","stateID":"48","stateName":"New Mexico"});
db.territoryState.save({"territoryID":"4","territoryName":"Southwest","stateID":"18","stateName":"Guam"});
db.territoryState.save({"territoryID":"4","territoryName":"Southwest","stateID":"6","stateName":"Arizona"});
db.territoryState.save({"territoryID":"4","territoryName":"Southwest","stateID":"9","stateName":"California"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"15","stateName":"Florida"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"3","stateName":"Alabama"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"27","stateName":"Kentucky"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"42","stateName":"North Carolina"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"17","stateName":"Georgia"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"39","stateName":"Mississippi"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"61","stateName":"Puerto Rico"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"67","stateName":"South Carolina"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"72","stateName":"Tennessee"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"75","stateName":"Virginia"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"76","stateName":"Virgin Islands"});
db.territoryState.save({"territoryID":"5","territoryName":"Southeast","stateID":"81","stateName":"West Virginia"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"83","stateName":"Yukon Territory"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"60","stateName":"Prince Edward Island"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"57","stateName":"Ontario"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"69","stateName":"Saskatchewan"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"63","stateName":"Quebec"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"45","stateName":"Newfoundland"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"41","stateName":"Brunswick"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"51","stateName":"Northwest Territories"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"49","stateName":"Nova Scotia"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"29","stateName":"Labrador"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"31","stateName":"Manitoba"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"1","stateName":"Alberta"});
db.territoryState.save({"territoryID":"6","territoryName":"Canada","stateID":"7","stateName":"British Columbia"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"87","stateName":"Ain"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"88","stateName":"Aisne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"89","stateName":"Allier"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"90","stateName":"Alpes-de-Haute Provence"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"91","stateName":"Alpes (Haute)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"92","stateName":"Alpes-Maritimes"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"93","stateName":"Ardèche"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"94","stateName":"Ardennes"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"95","stateName":"Ariège"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"96","stateName":"Aube"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"97","stateName":"Aude"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"98","stateName":"Aveyron"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"99","stateName":"Bouches du Rhône"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"100","stateName":"Calvados"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"101","stateName":"Cantal"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"102","stateName":"Charente"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"103","stateName":"Charente-Maritime"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"104","stateName":"Cher"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"105","stateName":"Corrèze"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"106","stateName":"Corse"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"107","stateName":"Côte d'Or"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"108","stateName":"Côtes-d'Armor"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"109","stateName":"Creuse"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"110","stateName":"Dordogne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"111","stateName":"Toubs"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"112","stateName":"Drôme"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"113","stateName":"Eure"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"114","stateName":"Eure et Loir"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"115","stateName":"Finistère"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"116","stateName":"Gard"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"117","stateName":"Garonne (Haute)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"118","stateName":"Gers"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"119","stateName":"Gironde"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"120","stateName":"Hérault"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"121","stateName":"Ille et Vilaine"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"122","stateName":"Indre"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"123","stateName":"Indre et Loire"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"124","stateName":"Isère"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"125","stateName":"Jura"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"126","stateName":"Landes"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"127","stateName":"Loir et Cher"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"128","stateName":"Loire"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"129","stateName":"Loire (Haute)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"130","stateName":"Loire Atlantique"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"131","stateName":"Loiret"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"132","stateName":"Lot"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"133","stateName":"Lot et Garonne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"134","stateName":"Lozère"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"135","stateName":"Maine et Loire"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"136","stateName":"Manche"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"137","stateName":"Marne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"138","stateName":"Marne (Haute)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"139","stateName":"Mayenne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"140","stateName":"Meurthe et Moselle"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"141","stateName":"Meuse"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"142","stateName":"Morbihan"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"143","stateName":"Moselle"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"144","stateName":"Nièvre"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"145","stateName":"Nord"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"146","stateName":"Oise"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"147","stateName":"Orne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"148","stateName":"Pas de Calais"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"149","stateName":"Puy de Dôme"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"150","stateName":"Pyrénées Atlantiques"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"151","stateName":"Pyrénées (Hautes)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"152","stateName":"Pyrénées Orientales"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"153","stateName":"Rhin (Bas)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"154","stateName":"Rhin (Haut)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"155","stateName":"Rhône"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"156","stateName":"Saône (Haute)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"157","stateName":"Saône et Loire"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"158","stateName":"Sarthe"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"159","stateName":"Savoie"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"160","stateName":"Savoie Haute"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"161","stateName":"Seine (Paris)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"162","stateName":"Seine Maritime"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"163","stateName":"Seine et Marne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"164","stateName":"Yveline"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"165","stateName":"Sèvres (Deux)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"166","stateName":"Somme"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"167","stateName":"Tarne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"168","stateName":"Tarne et Garonne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"169","stateName":"Var"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"170","stateName":"Vaucluse"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"171","stateName":"La Vendée"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"172","stateName":"Vienne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"173","stateName":"Vienne (Haute)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"174","stateName":"Vosges"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"175","stateName":"Yonne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"176","stateName":"Belford (Territoire de)"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"177","stateName":"Essonne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"178","stateName":"Hauts de Seine"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"179","stateName":"Seine Saint Denis"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"180","stateName":"Val de Marne"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"181","stateName":"Val d'Oise"});
db.territoryState.save({"territoryID":"7","territoryName":"France","stateID":"84","stateName":"France"});
db.territoryState.save({"territoryID":"8","territoryName":"Germany","stateID":"85","stateName":"Brandenburg"});
db.territoryState.save({"territoryID":"8","territoryName":"Germany","stateID":"86","stateName":"Saxony"});
db.territoryState.save({"territoryID":"8","territoryName":"Germany","stateID":"8","stateName":"Bayern"});
db.territoryState.save({"territoryID":"8","territoryName":"Germany","stateID":"19","stateName":"Hessen"});
db.territoryState.save({"territoryID":"8","territoryName":"Germany","stateID":"20","stateName":"Hamburg"});
db.territoryState.save({"territoryID":"8","territoryName":"Germany","stateID":"53","stateName":"Nordrhein-Westfalen"});
db.territoryState.save({"territoryID":"8","territoryName":"Germany","stateID":"70","stateName":"Saarland"});
db.territoryState.save({"territoryID":"9","territoryName":"Australia","stateID":"71","stateName":"Tasmania"});
db.territoryState.save({"territoryID":"9","territoryName":"Australia","stateID":"64","stateName":"Queensland"});
db.territoryState.save({"territoryID":"9","territoryName":"Australia","stateID":"66","stateName":"South Australia"});
db.territoryState.save({"territoryID":"9","territoryName":"Australia","stateID":"62","stateName":"Palau"});
db.territoryState.save({"territoryID":"9","territoryName":"Australia","stateID":"50","stateName":"New South Wales"});
db.territoryState.save({"territoryID":"9","territoryName":"Australia","stateID":"34","stateName":"Marshall Islands"});
db.territoryState.save({"territoryID":"9","territoryName":"Australia","stateID":"38","stateName":"Northern Mariana Islands"});
db.territoryState.save({"territoryID":"9","territoryName":"Australia","stateID":"16","stateName":"Micronesia"});
db.territoryState.save({"territoryID":"9","territoryName":"Australia","stateID":"77","stateName":"Victoria"});
db.territoryState.save({"territoryID":"10","territoryName":"United Kingdom","stateID":"14","stateName":"England"});